defaults:
  # - /llm@plan_config.llm: openai_chat
  - /instruct@plan_config.instruct: zero_shot_prompt

_target_: 'src.planner.ZeroShotReactPlanner'
_recursive_: False
_partial_: True

plan_config:
    replanning_threshold: 40 # max number of times the LLM is allowed to plan to finish the task
    planning_mode: "cot"
    constrained_generation: False
    objects_response: True
    objects_response_include_states: False
    centralized: False
    enable_rag: False # If we want to use RAG or not
    rag_dataset_dir: "" # The path to the rag_data_source_name folder
    rag_data_source_name: "" # rag_data_source_name folder itself
    example_type: "react" # The prompting format

    # UserProfileRAG
    enable_user_profile_rag: False # Activate UserProfileRAG
    #TODO: should change the path
    user_profile_memory_path: "/HabitatLLM/resource/user_profile_memory/gpt-4o/scenes" # UserProfile memory file path
    user_profile_top_k: 5 # Number of knowledge items to retrieve in UserProfile RAG
